# Generated by Django 3.0.4 on 2020-05-01 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_item_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='chatergory',
            field=models.CharField(choices=[('S', 'Shirt'), ('SW', 'Sport ware'), ('OW', 'Outware')], default='S', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='lable',
            field=models.CharField(choices=[('P', 'primary'), ('S', 'secondry'), ('D', 'danger ')], default='P', max_length=1),
            preserve_default=False,
        ),
    ]
