# Generated by Django 3.0.4 on 2020-05-01 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_auto_20200501_0730'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='slug',
            field=models.SlugField(default='default_product'),
            preserve_default=False,
        ),
    ]
