# Generated by Django 3.0.4 on 2020-05-01 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_item_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='d_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
