# Generated by Django 3.0.4 on 2020-05-01 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_orderitem_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='quantity',
        ),
    ]
