# Generated by Django 3.0.4 on 2020-05-06 17:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cart', '0011_auto_20200501_1144'),
    ]

    operations = [
        migrations.CreateModel(
            name='BilligAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_address', models.CharField(max_length=225)),
                ('apartment_address', models.CharField(max_length=100)),
                ('contries', models.CharField(choices=[('P', 'pakistan'), ('AF', 'Afghanstan'), ('In', 'India')], max_length=5)),
                ('zip', models.CharField(max_length=100)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='billing_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cart.BilligAddress'),
        ),
    ]
