# Generated by Django 3.0.4 on 2020-05-09 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0018_auto_20200509_1158'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='redunf_granted',
            new_name='refund_granted',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='redunf_requested',
            new_name='refund_requested',
        ),
    ]
